package packets

// CharacterInfo represents the character information structure used in various packets
// and shared across the FFXI server architecture.
type CharacterInfo struct {
	RaceID            uint16    // Race ID (mon_no)
	MainJobID         uint8     // Main job ID (mjob_no)
	SubJobID          uint8     // Sub job ID (sjob_no)
	FaceModelID       uint16    // Face model ID (face_no)
	TownNumber        uint8     // Town/Nation ID (town_no)
	GenFlag           uint8     // Unknown flag, always 0 (gen_flag)
	HairModelID       uint8     // Hair model ID (hair_no)
	CharacterSize     uint8     // Character size: 0=Small, 1=Medium, 2=Large (size)
	WorldNumber       uint16    // Unknown world number (world_no)
	GrapIDTbl         [8]uint16 // Model IDs: [0]=calculated, [1]=head, [2]=body, etc (GrapIDTbl)
	ZoneNumber        uint8     // Current zone ID (low byte) (zone_no)
	MainJobLevel      uint8     // Main job level (mjob_level)
	OnlineStatus      uint8     // Online status: 0=hidden(/anon), 1=visible (open_flag)
	GMCallCounter     uint8     // GM call counter (unused by client) (GMCallCounter)
	Version           uint16    // Version, usually 2 (version)
	FishingSkill      uint8     // Fishing skill level (skill1)
	ZoneNum2          uint8     // Zone ID high byte (zone_no2)
	SandyRank         uint8     // San d'Oria rank (TC_OPERATION_WORK_USER_RANK_LEVEL_SD_)
	BastokRank        uint8     // Bastok rank (TC_OPERATION_WORK_USER_RANK_LEVEL_BS_)
	WindyRank         uint8     // Windurst rank (TC_OPERATION_WORK_USER_RANK_LEVEL_WS_)
	ErrCounter        uint8     // Error counter, always 0 (ErrCounter)
	SandyFame         uint16    // San d'Oria fame (TC_OPERATION_WORK_USER_FAME_SD_COMMON_)
	BastokFame        uint16    // Bastok fame (TC_OPERATION_WORK_USER_FAME_BS_COMMON_)
	WindyFame         uint16    // Windurst fame (TC_OPERATION_WORK_USER_FAME_WS_COMMON_)
	NorgFame          uint16    // Norg fame (TC_OPERATION_WORK_USER_FAME_DARK_GUILD_)
	PlayTimeSeconds   uint32    // Play time in seconds (PlayTime)
	UnlockedJobsFlag  uint32    // Unlocked jobs flag mask (get_job_flag)
	JobLevels         [16]uint8 // Job levels array (first slot unused) (job_lev)
	FirstLoginDate    uint32    // First login timestamp (FirstLoginDate)
	GilAmount         uint32    // Current gil amount (Gold)
	WoodworkingSkill  uint8     // Woodworking skill level (skill2)
	SmithingSkill     uint8     // Smithing skill level (skill3)
	GoldsmithingSkill uint8     // Goldsmithing skill level (skill4)
	ClothcraftSkill   uint8     // Clothcraft skill level (skill5)
	ChatCounter       uint32    // Chat counter (unused by client) (ChatCounter)
	PartyCounter      uint32    // Party counter (unused by client) (PartyCounter)
	LeathercraftSkill uint8     // Leathercraft skill level (skill6)
	BonecraftSkill    uint8     // Bonecraft skill level (skill7)
	AlchemySkill      uint8     // Alchemy skill level (skill8)
	CookingSkill      uint8     // Cooking skill level (skill9)
}
